### ISSUE TITLE
BlueLake添加微信模块 | ━Start。平常心_

### ISSUE THREAD

**Issue by 841809077** [841809077/841809077.github.io#73]
https://841809077.github.io/2018/11/21/BlueLake%E6%B7%BB%E5%8A%A0%E5%BE%AE%E4%BF%A1%E6%A8%A1%E5%9D%97.html

**Comment by zcl1021** [comment]
不行呀

**Comment by zcl1021** [comment]
Unhandled rejection Error: H:\blog\themes\BlueLake\layout\base.jade:65
    63|               block tocmodel
    64|             each item in theme.widgets
  > 65|               != partial('_widget/' + item + '.jade')
    66|         else
    67|           .layout-r.hidden_mid_and_down: #sidebar
    68|             each item in theme.widgets

Partial _widget/weixn.jade does not exist. (in index.jade)
    at Object.partial (H:\blog\node_modules\hexo\lib\plugins\helper\partial.js:16:11)
    at eval (eval at exports.compile (H:\blog\node_modules\jade\lib\index.js:218:8), <anonymous>:1323:33)
    at eval (eval at exports.compile (H:\blog\node_modules\jade\lib\index.js:218:8), <anonymous>:1341:4)
    at eval (eval at exports.compile (H:\blog\node_modules\jade\lib\index.js:218:8), <anonymous>:1781:22)
    at res (H:\blog\node_modules\jade\lib\index.js:219:38)
    at viewFn._compiled (H:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (H:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at H:\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (H:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at H:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (H:\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Unhandled rejection Error: H:\blog\themes\BlueLake\layout\base.jade:65
    63|               block tocmodel
    64|             each item in theme.widgets
  > 65|               != partial('_widget/' + item + '.jade')
    66|         else
    67|           .layout-r.hidden_mid_and_down: #sidebar
    68|             each item in theme.widgets

Partial _widget/weixn.jade does not exist. (in index.jade)
    at Object.partial (H:\blog\node_modules\hexo\lib\plugins\helper\partial.js:16:11)
    at eval (eval at exports.compile (H:\blog\node_modules\jade\lib\index.js:218:8), <anonymous>:1323:33)
    at eval (eval at exports.compile (H:\blog\node_modules\jade\lib\index.js:218:8), <anonymous>:1341:4)
    at eval (eval at exports.compile (H:\blog\node_modules\jade\lib\index.js:218:8), <anonymous>:1781:22)
    at res (H:\blog\node_modules\jade\lib\index.js:219:38)
    at viewFn._compiled (H:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (H:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at H:\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (H:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at H:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (H:\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
